config/routes.rb
# -*- encoding : utf-8 -*-

LiberdadeHumana::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # 1. user routes
  devise_for :users

  # 2. contact routes
  get '/contact' => 'site#contact', as: :contact
  post '/contact' => 'site#send_contact', as: :send_contact

  get '/ranking' => 'site#ranking', as: :ranking
  get '/pais/:name' => 'site#country', as: :country

  root :to => 'site#index'
end

app/controllers/site_controller.rb
# -*- encoding : utf-8 -*-
class SiteController < ApplicationController

  before_filter Proc.new {
    @last_edition = Edition.last
    @penultimate_edition_values = Edition.last(2).first.values
    @countries = Country.order('name ASC')
  }

  def index
    @values = @last_edition.values.order('total DESC')
  end

  def ranking
    @values = @last_edition.values.order('total DESC')
  end

  def country
    @countries.each do |c|
      @country = c if c.name.parameterize('-') == params[:name]
    end

    unless @country.nil?
      @values = @country.values.includes(:edition).
        order('editions.created_at ASC')
      @editions = Edition.order('created_at ASC')
    else
      raise ActionController::RoutingError
    end

  end

  # CONTACT BEGIN

  def contact
    @contact = Page.where('indicator = ?', Page::PAGES[:contact]).first
    @contact_form = Contact.new

    raise ActionController::RoutingError unless @contact.published
  end

  def send_contact
    @contact = Page.where('indicator = ?', Page::PAGES[:contact]).first
    @contact_form = Contact.new(params[:contact])

    if @contact_form.save
      redirect_to(contact_path, :notice => "Mensagem enviada com sucesso.")
    else
      render :action => :contact
    end
  end

  # CONTACT END
end

app/views/site/_comparate_box.html.erb
<div class="qbox">
  <h3><i class="icon-search pull-right"></i>Compare os países</h3>

  <form>
    <p>Faça uma comparação entre dois países e veja a diferenças
    de pontuação para cada uma dos componentes do Índice.</p>

    <hr />

    <div class="app-country-field">
      <select data-placeholder="Escolha um país" class="chzn-select" style="width:100%;" tabindex="0">
        <% @countries.each do |c| %>
        <option value="<%= c.id %>"><%= c.name %></option>
        <% end %>
      </select>
    </div>

    <p style="text-align:center;" class="app-vs">Vs.</p>

    <div class="app-country-field">
      <select data-placeholder="Escolha um país" class="chzn-select" style="width:100%;" tabindex="0">
        <% @countries.each do |c| %>
          <option value="<%= c.id %>"><%= c.name %></option>
        <% end %>
      </select>
    </div>

    <button class="btn btn-inverse btn-small">Comparar</button>
  </form>
</div>

app/views/site/contact.html.erb
<h3><%= @contact.title %></h3>

<%= @contact.content.html_safe %>

<div id="main_content" class="contact_page">
  <%= content_tag(:p, notice, :class => 'notice') if notice %>

  <%= simple_form_for(@contact_form, :url => send_contact_path) do |f| %>
    <div class="inputs">
      <%= f.input :name %>
      <%= f.input :email %>
      <%= f.input :message, :as => :text %>
    <div>

    <div class="actions">
      <%= f.button :submit, 'Enviar mensagem' %>
    </div>
  <% end %>
</div>

app/views/site/country.html.erb
<div id="app-country-title" class="app-country-<%= @country.code %>">
  <h2><%= @country.name %></h2>
</div>

<div id="app-country-info">
  <div class="row-fluid">

    <p class="country-position span2">
      <span>Posição</span>

      <strong>23º</strong>

      <span>9.9<br />
        <em>Pontuação global</em>
      </span>
    </p>

    <p class="country-thumbnail span3">
      <%= image_map_tag(@country.name) %>
    </p>

    <div class="country-graph span7">

    </div>

  </div>
</div>


<%= content_for :scripts do %>
  <script src="http://code.highcharts.com/highcharts.js"></script>
  <script type="text/javascript">

  $(function () {
    $('#app-country-info .country-graph').highcharts({
      chart: {
        type: 'line'
      },
      title: { text: null },
      xAxis: {
        categories: [ <%= (@editions.collect { |e| e.name } * ',').html_safe %> ]
      },
      yAxis: {
        title: { text: null },
        plotLines: [{ value: 0, width: 1, color: '#fff' }]
      },
      legend: { enabled: false },
      series: [{
        color: '#66a620',
        name: '<%= escape_javascript(@country.name) %>',
        data: [ <%= (@values.collect { |c| c.total } * ',').html_safe %> ]
      }]
    });
  });

</script>

<% end %>

app/views/site/index.html.erb
<div id="map">
</div>

<div class="row-fluid" id="app-map-colors-degree">
  <p class="span6">Menos livres</p>
  <p class="span6">Mais livres</p>
</div>

<div class="body-text">

  <div class="container-fluid">

    <div class="row-fluid">

			<!--west pane span9-->
			<div class="span9">
				<div class="row-fluid">
					<h1>Os campeões de liberdade</h1>
				</div>

        <div class="row-fluid hotproperties">

          <% @values.limit(3).each.with_index do |v, i| %>
            <div class="span4 set-equal-heights-js freer">
              <div class="thumbnail">
                <%= link_to image_map_tag(v.country.name), '#' %>

                <div class="caption">
                  <%= link_to v.country.name, '#', class: 'prop-title' %>

								  <p class="app-home-ranking-detail">
                    <strong><%= i + 1 %>º</strong>
                    <strong><%= v.total.round(2) %><em>pontuação global</em>
                    </strong>

                    <%
                      old_value = @penultimate_edition_values.
                        where(country_id: v.country.id).first

                      variation = v.total - old_value.total unless old_value.nil?
                    %>

                    <strong>
                      <% if    variation < 0 %>
                        <i class="icon-chevron-down"></i>
                        <%= variation.round(2).abs %>
                      <% elsif variation > 0 %>
                        <i class="icon-chevron-up"></i>
                        <%= variation.round(2).abs %>
                      <% end %>
                    </strong>
								  </p>

                  <ul class="list-btns">
                    <li>
                      <a href="property.html"><i class="icon-info-sign"></i>Detalhes</a>
                    </li>
                  </ul>
							  </div>
              </div>
            </div>
          <% end %>

        </div>

			</div><!--end of west pane span9-->

			<!-- east pane with width of span3 -->
			<div class="span3">
        <%= render partial: 'comparate_box' %>
			</div>
			<!-- end of span3 -->

		</div>
	</div>
</div>

<%= content_for :scripts do %>
  <script type="text/javascript">
    var gdp_data = {
      <%= (@values.
        collect { |v| "'#{v.country.code}': #{v.total}" } * ',').html_safe %>
    };

    $(function () {
      $('#map').vectorMap({
          backgroundColor: 'transparent', zoomOnScroll: false,
          regionsSelectable: true, regionsSelectableOne: true,
          zoomStep: 1.2,
          series: {
            regions: [{
              values: gdp_data,
              scale: ['#ad0330', '#da7c38', '#d8be1e', '#a3da39', '#66a620'],
              normalizeFunction: 'linear'
            }]
          },
          onRegionLabelShow: function(e, el, code){
            el.html(el.html()+ ' (' + gdp_data[code] + ')');
          }
      });
    });
  </script>
<% end %>

app/views/site/ranking.html.erb
<div id="app-top-highlight">
  <%= render partial: 'comparate_box' %>
</div>

<div class="body-text">

	<h1 class="app-title">Ranking dos países</h1>

  <% free = @values.where('total <= 10.0 AND total >= 8.0') %>

  <h2 class="app-title free">
    <strong>Livres</strong>
    <em>(10 - 8)</em>
  </h2>

  <div class="app-ranking">
    <% free.each.with_index do |v, i| %>
      <%
        old_value = @penultimate_edition_values.where(country_id: v.country.id).
          first

        variation = v.total - old_value.total unless old_value.nil?
      %>

      <div class="app-elem row-fluid">
	      <div class="span3 app-pos"><%= i + 1 %>º</div>

	      <div class="span9">
		      <h3><a href="#"><%= v.country.name %></a></h3>
		      <p>
		        <small><strong>Total: <%= v.total.round(2) %></strong></small><br />

            <% if    variation < 0 %>
              <small>Variação: <i class="icon-chevron-down"></i>
              <%= variation.round(2).abs %></small>
            <% elsif variation > 0 %>
              <small>Variação: <i class="icon-chevron-up"></i>
              <%= variation.round(2).abs %></small>
            <% end %>
		      </p>
	      </div>
      </div>
    <% end %>
  </div>

  <% mostly_free = @values.where('total < 8.0 AND total >= 7.0') %>

  <h2 class="app-title mostly-free">
    <strong>Majoritariamente livres</strong>
    <em>(7.9 - 7)</em>
  </h2>

  <div class="app-ranking">
    <% mostly_free.each.with_index do |v, i| %>
      <%
        old_value = @penultimate_edition_values.where(country_id: v.country.id).
          first

        variation = v.total - old_value.total unless old_value.nil?
      %>

      <div class="app-elem row-fluid">
	      <div class="span3 app-pos"><%= i + 1 %>º</div>

	      <div class="span9">
		      <h3><a href="#"><%= v.country.name %></a></h3>
		      <p>
		        <small><strong>Total: <%= v.total.round(2) %></strong></small><br />

            <% if    variation < 0 %>
              <small>Variação: <i class="icon-chevron-down"></i>
              <%= variation.round(2).abs %></small>
            <% elsif variation > 0 %>
              <small>Variação: <i class="icon-chevron-up"></i>
              <%= variation.round(2).abs %></small>
            <% end %>
		      </p>
	      </div>
      </div>
    <% end %>
  </div>

  <% moderately_free = @values.where('total < 7 AND total >= 6.0') %>

  <h2 class="app-title moderately-free">
    <strong>Moderadamente livres</strong>
    <em>(6.9 - 6)</em>
  </h2>

  <div class="app-ranking">
    <% moderately_free.each.with_index do |v, i| %>
      <%
        old_value = @penultimate_edition_values.where(country_id: v.country.id).
          first

        variation = v.total - old_value.total unless old_value.nil?
      %>

      <div class="app-elem row-fluid">
	      <div class="span3 app-pos"><%= i + 1 %>º</div>

	      <div class="span9">
		      <h3><a href="#"><%= v.country.name %></a></h3>
		      <p>
		        <small><strong>Total: <%= v.total.round(2) %></strong></small><br />

            <% if    variation < 0 %>
              <small>Variação: <i class="icon-chevron-down"></i>
              <%= variation.round(2).abs %></small>
            <% elsif variation > 0 %>
              <small>Variação: <i class="icon-chevron-up"></i>
              <%= variation.round(2).abs %></small>
            <% end %>
		      </p>
	      </div>
      </div>
    <% end %>
  </div>

  <% mostly_unfree = @values.where('total < 6 AND total >= 5.0') %>

  <h2 class="app-title mostly-unfree">
    <strong>Majoritariamente não livres</strong>
    <em>(5.9 - 5)</em>
  </h2>

  <div class="app-ranking">
    <% mostly_unfree.each.with_index do |v, i| %>
      <%
        old_value = @penultimate_edition_values.where(country_id: v.country.id).
          first

        variation = v.total - old_value.total unless old_value.nil?
      %>

      <div class="app-elem row-fluid">
	      <div class="span3 app-pos"><%= i + 1 %>º</div>

	      <div class="span9">
		      <h3><a href="#"><%= v.country.name %></a></h3>
		      <p>
		        <small><strong>Total: <%= v.total.round(2) %></strong></small><br />

            <% if    variation < 0 %>
              <small>Variação: <i class="icon-chevron-down"></i>
              <%= variation.round(2).abs %></small>
            <% elsif variation > 0 %>
              <small>Variação: <i class="icon-chevron-up"></i>
              <%= variation.round(2).abs %></small>
            <% end %>
		      </p>
	      </div>
      </div>
    <% end %>
  </div>

  <% unfree = @values.where('total < 5 AND total >= 0.0') %>

  <h2 class="app-title unfree">
    <strong>Não livres</strong>
    <em>(4.9 - 0)</em>
  </h2>

  <div class="app-ranking">
    <% unfree.each.with_index do |v, i| %>
      <%
        old_value = @penultimate_edition_values.where(country_id: v.country.id).
          first

        variation = v.total - old_value.total unless old_value.nil?
      %>

      <div class="app-elem row-fluid">
	      <div class="span3 app-pos"><%= i + 1 %>º</div>

	      <div class="span9">
		      <h3><a href="#"><%= v.country.name %></a></h3>
		      <p>
		        <small><strong>Total: <%= v.total.round(2) %></strong></small><br />

            <% if    variation < 0 %>
              <small>Variação: <i class="icon-chevron-down"></i>
              <%= variation.round(2).abs %></small>
            <% elsif variation > 0 %>
             <small> Variação: <i class="icon-chevron-up"></i>
              <%= variation.round(2).abs %></small>
            <% end %>
		      </p>
	      </div>
      </div>
    <% end %>
  </div>

</div>